const ASSOCIATIONSarray = [
  {
    id: 1,
    email: "test@gmail.com",
    password: "not saved here...",
    associationName: "PawsAdopt",
    country: "Portugal",
    state: "Madeira",
    city: "Funchal",
    contactPhone: "+351 916477856",
    contactEmail: "test2@gmail.com",
    description: "blablablablablabla",
    photo: ["http://pets-images.dev-apis.com/pets/dog25.jpg"],
    userType: "association",
  },
  {
    id: 2,
    email: "test3@gmail.com",
    password: "not saved here...",
    associationName: "PawsAdopt2",
    country: "Portugal",
    state: "Madeira",
    city: "Funchal",
    contactPhone: "+351 916477856",
    contactEmail: "test4@gmail.com",
    description: "blablablablablabla",
    photo: [],
    userType: "association",
  },
  {
    id: 3,
    email: "test5@gmail.com",
    password: "not saved here...",
    associationName: "PawsAdopt3",
    country: "Portugal",
    state: "Lisbon",
    city: "Lisbon",
    contactPhone: "+351 916477856",
    contactEmail: "test6@gmail.com",
    description: "blablablablablabla",
    photo: ["http://pets-images.dev-apis.com/pets/dog25.jpg"],
    userType: "association",
  },
];

export default ASSOCIATIONSarray;