import { useState } from "react";
import { useNavigate } from "react-router-dom";

const Register = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [userType, setUserType] = useState("");
  const navigate = useNavigate(); //To navigate back to previous pages, use the React useNavigation Hook.

  //just for testing purposes - user id will be generated by Firebase auth (the next function does not ensures the number is unique!):
  function generateRandomId() {
    return Math.floor(Math.random() * 1000);
  }
  const handleRegistration = function (userType) {
    //common parameters to all users:
    const newUser = {
      id: generateRandomId(),
      email: email,
      password: password,
      userType: userType,
    };

    // if (userType === "association") {
    //   // newUser.associationName = associationName;
    //   ASSOCIATIONSarray.push(newUser);
    //   console.log("ASSOCIATIONSarray", ASSOCIATIONSarray);
    // } else if (userType === "volunteer") {
    //   VOLUNTEERSarray.push(newUser);
    //   console.log("VOLUNTEERSarray", VOLUNTEERSarray);
    // } else {
    //   REGULARUSERSarray.push(newUser);
    //   console.log("REGULARUSERSarray", REGULARUSERSarray);
    // }
    console.log("newUser", newUser);
    navigate("/profile", { state: { newUser } });
  };

  return (
    <div className="login-container flex flex-col items-center justify-center pt-[4rem]">
      <h1 className="text-darkest mb-[3rem] font-bold"> REGISTER AS: </h1>
      <form>
        <div className="radioButton text-darkest mb-[2rem] flex space-x-[4rem]">
          <label>
            <input
              type="radio"
              value="regular"
              name="userType"
              className="radio-button mr-[1rem]"
              onChange={() => setUserType("regular")}
            />
            Regular User
          </label>
          <label>
            <input
              type="radio"
              value="volunteer"
              name="userType"
              className="radio-button mr-[1rem]"
              onChange={() => setUserType("volunteer")}
            />
            Volunteer
          </label>
          <label>
            <input
              type="radio"
              value="association"
              name="userType"
              className="radio-button mr-[1rem]"
              onChange={() => setUserType("association")}
            />
            Association
          </label>
        </div>
      </form>

      <form className="flex flex-col ">
        {/* {userType === "association" ? (
          <label className="text-darkest pb-[1.8rem] text-start font-[1.125rem]">
            NAME:
            <br />
            <input
              type="text"
              className="user-data-input w-[22.31rem]"
              value={associationName}
              onChange={(e) => setAssociationName(e.target.value)}
            />
          </label>
        ) : (
          <div className="flex flex-col">
            <label className="text-darkest pb-[1.8rem] text-start font-[1.125rem]">
              FIRST NAME:
              <br />
              <input
                type="text"
                className="user-data-input w-[22.31rem]"
                value={nameFirst}
                onChange={(e) => setNameFirst(e.target.value)}
              />
            </label>
            <label className="text-darkest pb-[1rem] text-start font-[1.125rem]">
              LAST NAME:
              <br />
              <input
                type="text"
                className="user-data-input w-[22.31rem]"
                value={nameLast}
                onChange={(e) => setNameLast(e.target.value)}
              />
            </label>
          </div>
        )} */}

        <label className="text-darkest pb-[1rem] text-start font-[1.125rem]">
          EMAIL:
          <br />
          <input
            type="text"
            className="user-data-input w-[22.31rem]"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </label>
        <label className="text-darkest text-start">
          PASSWORD:
          <br />
          <input
            type="password"
            className="user-data-input w-[22.31rem]"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </label>
        <div className="mb-[0rem] mt-[0.5rem] self-center">
          <button
            className="custom-button-over-white-bg h-[3.0rem] w-[7.5rem]"
            onClick={() => handleRegistration(userType)}
          >
            REGISTER
          </button>
        </div>
      </form>
      <div className="flex items-center justify-center pt-[0rem]">
        <h3 className="text-darkest pr-[2rem]"> Already have an account? </h3>
        <button
          className="custom-button-over-white-bg ] h-[3.0rem] w-[6.5rem]"
          onClick={() => navigate("/login")}
        >
          LOG IN
        </button>
      </div>
    </div>
  );
};

export default Register;
